name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: greet
      run: | 
        echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
        echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
        echo "choice is ${{ github.event.inputs.selected_tag }}" / ${{ inputs.choice }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # เลือกเวอร์ชัน Node.js ที่คุณใช้งาน
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build Vue.js App
      run: npm run build