name: Run on Tag Version

on:
  workflow_dispatch:
    inputs:
      selected_tag:
        description: 'Select a tag version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Tags from GitHub API
      id: get_tags
      run: |
        sudo -i
        TAGS=$(curl -s "https://api.github.com/repos/anuntawee/my-app/tags" | jq -r '.[].name')
        echo "Tags from API: $TAGS"
        echo "::set-output name=tags::$TAGS"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Display Available Tags
      run: |
        TAGS=${{ steps.get_tags.outputs.tags }}
        echo "Available tags: $TAGS"

    - name: Generate HTML Form
      id: generate_form
      run: |
        TAGS=${{ steps.get_tags.outputs.tags }}
        OPTIONS=""
        for tag in $TAGS; do
          OPTIONS="$OPTIONS<option value='$tag'>$tag</option>"
        done
        echo "::set-output name=options::$OPTIONS"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        TAGS=${{ steps.get_tags.outputs.tags }}
        echo "Available tags: $TAGS"

        # ดึง "tag version" ที่ผู้ใช้เลือก
        SELECTED_TAG=${{ github.event.inputs.selected_tag }}

        echo "Building and deploying for selected tag: $SELECTED_TAG"
