name: Get Tags from GitHub API

on:
  workflow_dispatch:

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Get Tags from GitHub API
      id: get_tags
      run: |
        TAGS=$(curl -s "https://api.github.com/repos/anuntawee/my-app/tags" | jq -r '.[].name')
        echo "TAGS=${TAGS}" >> $GITHUB_ENV

    - name: Display Tags
      run: |
        echo "Tags from GitHub API: $TAGS"

    - name: Use Tags Array
      run: |
        IFS=',' read -ra TAGS_ARRAY <<< "$TAGS"
        for tag in "${TAGS_ARRAY[@]}"; do
          echo "Processing tag: $tag"
          # Perform actions with each tag version
        done

  build_app:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # เลือกเวอร์ชัน Node.js ที่คุณใช้งาน
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build Vue.js App
      run: npm run build
