name: Get Tags from GitHub API

on:
  workflow_dispatch:
    inputs:
      selected_tag:
        description: 'Select a tag version'
        required: true

jobs:
  get_tags:
    runs-on: ubuntu-latest

    steps:
    - name: Get Tags from GitHub API
      id: get_tags
      run: |
        REPO_OWNER=anuntawee
        REPO_NAME=my-app
        TAGS=$(curl -s -H  "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/tags" | jq -r '.[].name')
        echo "TAGS=${TAGS}" >> $GITHUB_ENV

    - name: Display Tags
      run: |
        echo "Tags from GitHub API: $TAGS"
