name: CI

on:
  workflow_dispatch:
    inputs:
      selected_tag:
        description: 'Selected tag version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: greet
      run: | 
        echo "Building and deploying for selected tag: ${{ github.event.inputs.selected_tag }}"
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # เลือกเวอร์ชัน Node.js ที่คุณใช้งาน
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build Vue.js App
      run: npm run build